 export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

 export const REQUEST_ROBOTS_PENDING = 'PENDING';
 export const REQUEST_ROBOTS_SUCCESS = 'SUCCESS';
 export const REQUEST_ROBOTS_FAILED = 'FAILED';